trigger:
  branches:
    include:
      - main

schedules:
  - cron: "0 3 * * 4"
    displayName: "Weekly Release (Thu 03:00 UTC)"
    branches:
      include:
        - main
    always: true

pr: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

stages: 
- stage: build
  jobs:
  - template: jobs/bicep-lint-code.yml@ado-pipeline-templates
    parameters: 
      jobName: 'bicep_linter'
      azureSubscription: 'spn-platform-connectivity-development'

  - template: templates/bicep-environment-validation.yml
    parameters:
      dependsOn: [bicep_linter]
      azureSubscription: 'spn-platform-connectivity-development'
      environment: 'platform-connectivity-Development'
      environmentName: 'dev'

  - template: templates/bicep-environment-validation.yml
    parameters:
      dependsOn: [bicep_linter]
      azureSubscription: 'spn-platform-connectivity-production'
      environment: 'platform-connectivity-Production'
      environmentName: 'prd'

- template: templates/deploy-environment.yml
  parameters:
    azureSubscription: 'spn-platform-connectivity-development'
    environment: 'platform-connectivity-Development'
    environmentName: 'dev'

- template: templates/deploy-environment.yml
  parameters:
    azureSubscription: 'spn-platform-connectivity-production'
    environment: 'platform-connectivity-Production'
    environmentName: 'prd'
